version: "3.7"

services:

  multicraft_database:
    image: mariadb
    networks:
      - multicraft-internal
    volumes:
      - multicraft_mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=multicraft"
      - "MYSQL_USER=multicraft"
      - "MYSQL_PASSWORD=multicraft"
      - "MYSQL_DATABASE=multicraft"

  php:
    image: cookiesofdoom/mutlicraft-php
    build:
      context: ./
      dockerfile: image/php/Dockerfile
    networks:
      - multicraft-internal
    volumes:
      - /var/www/multicraft:/usr/src/app
    depends_on:
      - multicraft_database

  nginx:
    image: nginx
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - multicraft-internal
    volumes:
      - /var/www/multicraft:/usr/src/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - multicraft_database
    depends_on:
      - php

volumes:
  multicraft_mysql: {}

networks:
  multicraft-internal: {}